image: docker:latest

services:
  - docker:dind

before_script:
  # - DOCKER_PASSWORD="global var"
  - DOCKER_USER="$CI_PROJECT_NAMESPACE"
  - TAG=$(echo -n "$DOCKER_USER/${CI_PROJECT_NAME##docker-}:"; if [ "master" = "$CI_COMMIT_REF_NAME" ]; then echo "latest"; else echo "$CI_COMMIT_REF_NAME"; fi)
  - echo $TAG
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" 

build:
  stage: build
  script:
    - docker build --pull -t "$TAG" .
    - docker push "$TAG"
